import { LegalPageLayout } from "@/components/LegalPageLayout";

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="August 6, 2026">
      <h2>1. Acceptance of Terms</h2>
      <p>
        These Terms of Service ("Terms") govern your use of Clausly, operated by Mian Ather,
        doing business as Clausly ("Clausly," "we," "us"). By accessing or using Clausly, you
        agree to be bound by these Terms.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        Clausly is automation software that uses artificial intelligence to generate legal
        document drafts and analyze contract text. <strong>Clausly is not a law firm, does not
        provide legal advice, and does not create an attorney-client relationship</strong> of any
        kind. Documents and analyses produced by Clausly are for informational purposes only.
        You should always consult a licensed attorney before relying on, signing, or executing
        any legal document.
      </p>

      <h2>3. Eligibility</h2>
      <p>You must be at least 18 years old and able to form a binding contract to use Clausly.</p>

      <h2>4. Account Registration</h2>
      <p>
        You are responsible for maintaining the confidentiality of your account credentials and
        for all activity that occurs under your account.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use Clausly for any unlawful purpose or to generate fraudulent documents</li>
        <li>Attempt to reverse-engineer, scrape, or disrupt the platform</li>
        <li>Resell or redistribute Clausly's output as a competing service without permission</li>
        <li>Circumvent usage limits associated with your subscription tier</li>
      </ul>

      <h2>6. Your Content & Ownership</h2>
      <p>
        You retain ownership of the content you submit (party names, terms, contract text) and
        the documents Clausly generates for you. By submitting content, you grant Clausly a
        limited license to process that content solely to provide the service to you, including
        sending it to our AI processing provider as described in our{" "}
        <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>7. Subscription & Billing</h2>
      <p>
        Paid plans are billed on a recurring basis as described on our{" "}
        <a href="/pricing">Pricing</a> page. You may cancel your subscription at any time, which
        will stop future billing; see our <a href="/refund">Refund Policy</a> for details on
        refund eligibility. Free tier accounts are subject to usage limits described on the
        Pricing page.
      </p>

      <h2>8. Intellectual Property</h2>
      <p>
        The Clausly platform, including its design, branding, and underlying software, is the
        property of Clausly and may not be copied or reproduced without permission.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        Clausly is provided "as is" and "as available" without warranties of any kind, express or
        implied, including warranties of accuracy, merchantability, or fitness for a particular
        purpose. We do not warrant that documents generated by Clausly are legally sufficient,
        enforceable, or appropriate for your specific situation or jurisdiction.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Clausly and its operator shall not be liable for
        any indirect, incidental, special, or consequential damages arising from your use of the
        service, including but not limited to damages resulting from reliance on generated
        documents or analyses.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify and hold Clausly harmless from any claims arising out of your use
        of the service or violation of these Terms.
      </p>

      <h2>12. Termination</h2>
      <p>
        We may suspend or terminate your access to Clausly if you violate these Terms. You may
        stop using Clausly and delete your account at any time.
      </p>

      <h2>13. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the State of Utah, without regard to its conflict
        of laws principles.
      </p>

      <h2>14. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of Clausly after changes are
        posted constitutes acceptance of the updated Terms.
      </p>

      <h2>15. Contact</h2>
      <p>
        Questions about these Terms? Email us at{" "}
        <a href="mailto:support@clausly.net">support@clausly.net</a>.
      </p>
    </LegalPageLayout>
  );
}
